"""Generate self-contained, offline browser demos for Automotive Web Apps."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
PROJECTS={
'automotive-lead-referral':('Automotive Lead Follow-up & Referrals','Organize enquiries, next contact dates, vehicle interest and referral source. Demo only; does not send WhatsApp/SMS.','Leads',['New','Contacted','Test drive','Negotiation','Won','Lost'],['Contact','Vehicle interest','Salesperson'],'lead value'),
'commercial-vehicle-sales-financing':('Commercial Vehicle Sales & Financing Workflow','Track truck and commercial vehicle deals, documents and finance milestones.','Applications',['Enquiry','Documents','Finance review','Approved','Delivered','Declined'],['Customer','Vehicle','Sales owner'],'vehicle value'),
'car-rental-booking':('Car Rental Booking & Fleet Administration','Track reservations, fleet availability, checkout and returns for a rental desk.','Reservations',['Requested','Confirmed','Checked out','Returned','Cancelled'],['Customer','Vehicle','Branch'],'rental total'),
'car-rental-web-mobile':('Car Rental Web & Mobile Platform','Demo of a customer booking flow with fleet schedule and reservation tracking.','Bookings',['New','Confirmed','Picked up','Returned','Cancelled'],['Customer','Vehicle','Pickup location'],'booking total'),
'truck-profit-tracker':('Truck Income & Expense Tracker','Compare trip income with fuel, tolls, repairs and other operating costs.','Trips',['Planned','In progress','Settled','Needs review'],['Truck','Route','Driver'],'trip income'),
'auto-parts-inventory':('Auto Parts Sales & Inventory','Monitor parts stock, purchase cost, sales value and replenishment status.','Parts',['In stock','Low stock','On order','Backorder'],['Part number','Part','Supplier'],'stock value'),
'rental-fleet-operations':('Rental Fleet Operations Workspace','Track vehicle readiness, utilization, open rentals and operating costs.','Fleet vehicles',['Available','Reserved','Rented','Service','Retired'],['Vehicle','Branch','Fleet manager'],'asset value'),
'repair-shop-intake':('Repair Shop Intake & Signature Portal','Record vehicle intake, customer-approved work and completion. Demo signatures are typed names only.','Repair orders',['Checked in','Estimate','Approved','In repair','Ready','Collected'],['Customer','Vehicle','Advisor'],'approved estimate'),
'dealership-sales-crm':('Dealership Sales CRM & Dashboard','Follow showroom enquiries from first contact through sale and handover.','Opportunities',['New','Contacted','Visit','Test drive','Negotiation','Won','Lost'],['Customer','Vehicle','Salesperson'],'deal value'),
'showroom-inventory-manager':('Showroom Inventory Manager','Track each vehicle’s acquisition, preparation spend, asking price and sale status.','Vehicles',['In stock','Reserved','Sold','Under preparation'],['Stock number','Make and model','Branch'],'asking price'),
'vehicle-inspection-dashboard':('Vehicle Inspection Operations Dashboard','Schedule inspections, capture condition grades and follow up repair recommendations.','Inspections',['Booked','In progress','Needs repair','Passed','Released'],['Vehicle','Inspector','Inspection type'],'repair estimate'),
'car-detailing-crm':('Car Detailing Booking & CRM','Schedule detailing packages, track customer vehicles and record completed services.','Jobs',['Requested','Booked','In service','Ready','Collected'],['Customer','Vehicle','Package'],'service amount'),

'fleet-logistics-management':('Fleet & Logistics Management Platform','Monitor vehicle assignments, trip status, route utilization and operating cost.','Dispatches',['Planned','Dispatched','Delayed','Delivered','Closed'],['Vehicle','Route','Dispatcher'],'trip cost'),
'dealership-enquiry-to-sale':('Dealership Enquiry-to-Sale Dashboard','Follow enquiry source, showroom visits, test drives and deal conversion.','Enquiries',['New','Contacted','Visit','Test drive','Negotiation','Won','Lost'],['Customer','Vehicle interest','Salesperson'],'deal value'),
'dealership-finance-forecast':('Dealership Finance & Forecast Dashboard','Compare showroom sales, direct costs, margins and forecast targets.','Monthly results',['Actual','Forecast','At risk','Closed'],['Branch','Period','Manager'],'gross profit'),
'fleet-maintenance-costs':('Fleet Maintenance-Cost Dashboard','Track service intervals, downtime and vehicle repair spending.','Maintenance jobs',['Scheduled','Due','In repair','Ready','Overdue'],['Vehicle','Workshop','Fleet owner'],'repair cost'),
'fleet-operations-payments':('Fleet Operations & Outstanding-Payments Report','Review fleet activity, customer balances and payment collection status.','Accounts',['Current','Part paid','Overdue','Paid','Disputed'],['Customer','Vehicle / route','Account owner'],'outstanding balance'),
'dealer-workshop-kpis':('Combined Dealership & Workshop KPI System','Combine vehicle sales, service throughput and workshop profitability indicators.','KPI records',['On track','Watch','Action needed','Complete'],['Department','KPI','Owner'],'KPI amount'),
'vehicle-profit-stock-intelligence':('Vehicle Profitability & Stock-Intelligence Platform','Analyze vehicle acquisition investment, direct costs, realized sales margins and stock age.','Vehicles',['In stock','Reserved','Sold','Aged stock'],['Stock number','Make / model','Branch'],'vehicle investment'),
}
TEMPLATE=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>__TITLE__ · Astra demo</title><style>
:root{--ink:#172a27;--muted:#667772;--bg:#f2f5f3;--green:#096b5c;--line:#dce5e0;--white:#fff}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px Inter,system-ui,sans-serif}header{background:#103a33;color:white;padding:24px max(24px,calc((100% - 1240px)/2));display:flex;justify-content:space-between;align-items:center;gap:20px}header small{color:#abd1c1;text-transform:uppercase;letter-spacing:1px}header h1{margin:8px 0;font-size:26px}header p{margin:0;color:#c5d8d1}main{max-width:1240px;margin:28px auto;padding:0 20px}.actions,.filters{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:16px}button,.export{background:white;border:1px solid var(--line);padding:10px 14px;border-radius:8px;cursor:pointer;color:var(--ink);font:inherit;text-decoration:none}button.primary{background:var(--green);color:#fff;border-color:var(--green)}input,select{border:1px solid var(--line);background:white;padding:10px;border-radius:7px;font:inherit}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:13px}.card,.panel{background:white;border:1px solid var(--line);border-radius:11px;padding:18px}.card small{color:var(--muted)}.card b{font-size:23px;display:block;margin:10px 0}.panel{margin-top:16px}.panel h2{margin:0 0 14px;font-size:17px}.table{overflow:auto}table{border-collapse:collapse;width:100%;text-align:left}td,th{padding:12px;border-bottom:1px solid #edf1ef;white-space:nowrap}th{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.5px}.pill{background:#e4f3eb;color:#286449;padding:4px 8px;border-radius:20px;font-size:11px}.pill.warn{background:#fff0dc;color:#865d13}dialog{border:0;border-radius:14px;width:min(620px,95vw);padding:24px;box-shadow:0 15px 60px #071f1944}dialog::backdrop{background:#0a231d88}form{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{color:var(--muted);font-size:12px}label input,label select{display:block;width:100%;margin-top:5px}.full{grid-column:1/-1}.note{font-size:12px;color:var(--muted)}.flash{color:var(--green);min-height:20px}@media(max-width:800px){header{padding:18px;display:block}.stats{grid-template-columns:1fr 1fr}main{padding:0 12px}.card{padding:13px}}@media(max-width:460px){.stats{grid-template-columns:1fr 1fr}.card b{font-size:18px}}
</style><header><div><small>ASTRA · __GROUP__ WORKSPACE</small><h1>__TITLE__</h1><p>__DESC__</p></div><a class="export" href="../README.md">Project collection</a></header><main><div class="actions"><button class="primary" id="add">+ Add __SINGULAR__</button><button id="reset">Reset sample data</button><button id="csv">Export CSV</button><span class="note">Standalone demo · this browser only</span></div><div class="flash" id="flash" role="status"></div><section class="stats" id="stats"></section><section class="panel"><div class="filters"><h2 style="margin:0;flex:1">__PLURAL__</h2><input id="search" placeholder="Search records"><select id="status"><option value="">All statuses</option>__OPTIONS__</select><span id="count" class="note"></span></div><div class="table"><table><thead id="thead"></thead><tbody id="tbody"></tbody></table></div></section><p class="note">Sample entries are fictional. Records stay in local browser storage; they are not synced across devices or shared with a team. No messages, payments, financing decisions, signatures or external services are triggered.</p></main><dialog id="dlg"><h2 id="dlgtitle"></h2><form id="form"></form></dialog><script>
const C=__CONFIG__;const key='astra:'+location.pathname;const $=x=>document.getElementById(x);const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=n=>'PKR '+new Intl.NumberFormat('en-PK',{maximumFractionDigits:0}).format(+n||0);const today=new Date().toISOString().slice(0,10);const seed=C.seed.map((r,i)=>({id:Date.now()+i,...r}));let records=JSON.parse(localStorage.getItem(key)||'null')||seed;function save(){localStorage.setItem(key,JSON.stringify(records));render()}function render(){let q=$('search').value.toLowerCase(),s=$('status').value;let list=records.filter(r=>(!q||Object.values(r).join(' ').toLowerCase().includes(q))&&(!s||r.status===s));$('stats').innerHTML=[['Total '+C.plural,records.length],['Open / active',records.filter(r=>!C.closed.includes(r.status)).length],['Total '+C.valueLabel,money(records.reduce((a,r)=>a+(+r.value||0),0))],['Needs attention',records.filter(r=>r.status===C.attention||r.date<today&&!C.closed.includes(r.status)).length]].map(x=>`<div class="card"><small>${esc(x[0])}</small><b>${esc(x[1])}</b><small>Sample workspace</small></div>`).join('');let cols=['Record',...C.fields.map(f=>f.label),'Status','Owner','Date',C.valueLabel,''];$('thead').innerHTML='<tr>'+cols.map(x=>`<th>${esc(x)}</th>`).join('')+'</tr>'; $('tbody').innerHTML=list.map(r=>`<tr><td><b>${esc(r.name)}</b><br><small>${esc(r.ref)}</small></td>${C.fields.map(f=>`<td>${esc(r[f.key])}</td>`).join('')}<td><span class="pill ${r.status===C.attention?'warn':''}">${esc(r.status)}</span></td><td>${esc(r.owner)}</td><td>${esc(r.date)}</td><td>${money(r.value)}</td><td><button data-edit="${r.id}">Edit</button> <button data-del="${r.id}">Delete</button></td></tr>`).join('')||`<tr><td colspan="${cols.length}">No matching records. Add one to begin.</td></tr>`;$('count').textContent=`${list.length} shown`}
function openForm(item){let editing=!!item;let fields=[{key:'name',label:C.fields[0].label,type:'text'},...C.fields.slice(1),{key:'status',label:'Status',type:'select',options:C.statuses},{key:'owner',label:'Owner',type:'text'},{key:'date',label:'Due / activity date',type:'date'},{key:'value',label:C.valueLabel+' (PKR)',type:'number'}];$('dlgtitle').textContent=(editing?'Update ':'Add ')+C.singular;$('form').innerHTML=fields.map(f=>`<label>${esc(f.label)}${f.type==='select'?`<select name="${f.key}">${f.options.map(o=>`<option ${item?.[f.key]===o?'selected':''}>${esc(o)}</option>`).join('')}</select>`:`<input required name="${f.key}" type="${f.type}" ${f.type==='number'?'min="0" step="1"':''} value="${esc(item?.[f.key]??(f.key==='date'?today:f.key==='owner'?'Showroom team':f.key==='value'?0:''))}">`}</label>`).join('')+`<label class="full">Notes<input name="notes" value="${esc(item?.notes||'')}"></label><div class="full"><button type="button" id="cancel">Cancel</button> <button class="primary">Save record</button></div>`;$('cancel').onclick=()=>$('dlg').close();$('form').onsubmit=e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.target));data.value=Math.max(0,Number(data.value)||0);data.ref=item?.ref||C.prefix+'-'+String(records.length+1).padStart(4,'0');if(editing)records=records.map(r=>r.id===item.id?{...item,...data}:r);else records.unshift({id:Date.now(),...data});save();$('dlg').close();$('flash').textContent='Saved to this browser.'};$('dlg').showModal()}
$('add').onclick=()=>openForm(null);$('search').oninput=render;$('status').onchange=render;$('reset').onclick=()=>{if(confirm('Reset this project demo data in this browser?')){records=seed;save()}};$('csv').onclick=()=>{let rows=[['Reference','Record',...C.fields.map(f=>f.label),'Status','Owner','Date',C.valueLabel+' (PKR)','Notes'],...records.map(r=>[r.ref,r.name,...C.fields.map(f=>r[f.key]),r.status,r.owner,r.date,r.value,r.notes||''])];let csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=C.prefix.toLowerCase()+'-demo.csv';a.click();URL.revokeObjectURL(a.href)};$('tbody').onclick=e=>{let b=e.target.closest('button');if(b?.dataset.edit)openForm(records.find(r=>r.id==b.dataset.edit));if(b?.dataset.del&&confirm('Delete this sample record?')){records=records.filter(r=>r.id!=b.dataset.del);save()}};render();
</script></html>'''

def config_for(title,desc,plural,statuses,fields,value_label):
    # Field descriptors represent extra domain columns; the first is the primary project entity.
    configs=[]
    for i,label in enumerate(fields):
        key=['entity','detail','group'][i]
        configs.append({'key':key,'label':label,'type':'text'})
    demo_names=['Northside account','Harbor account','Central account','West account']
    if 'Vehicle' in plural or 'Fleet' in plural or 'Parts' in plural or 'Trips' in plural or 'Inspection' in plural or 'Repair' in plural or 'Reservation' in plural or 'Booking' in plural or 'Jobs' in plural:
        demo_names=['Toyota Corolla','Honda Civic','Suzuki Swift','Kia Sportage']
    seed=[]
    for i,n in enumerate(demo_names):
        st=statuses[min(i,len(statuses)-1)]
        d=(__import__('datetime').date.today()-__import__('datetime').timedelta(days=i*5)).isoformat()
        row={'name':n,'status':st,'owner':['Sam','Amina','Bilal','Nora'][i],'date':d,'value':[125000,89000,210000,67500][i],'notes':'Fictional sample entry','ref':f'AST-{i+1:04d}'}
        for j,f in enumerate(configs): row[f['key']]=['Priority account','Quarterly review','Karachi'][min(j,2)]
        seed.append(row)
    return {'title':title,'description':desc,'plural':plural,'singular':plural[:-1] if plural.endswith('s') else plural,'statuses':statuses,'fields':configs,'valueLabel':value_label,'closed':[x for x in statuses if x.lower() in ['complete','completed','closed','paid','won','lost','returned','collected','delivered','released','sold','cancelled','canceled','declined','placed']],'attention':next((x for x in statuses if any(k in x.lower() for k in ['overdue','exception','repair','backorder','action','dispute','blocked','review'])),statuses[-1]),'prefix':''.join(w[0] for w in plural.split()).upper(),'seed':seed}

def main():
    for path,(title,desc,plural,statuses,fields,value_label) in PROJECTS.items():
        folder=ROOT/path; folder.mkdir(parents=True,exist_ok=True)
        config=config_for(title,desc,plural,statuses,fields,value_label)
        html=TEMPLATE.replace('__TITLE__',title).replace('__DESC__',desc).replace('__PLURAL__',plural).replace('__SINGULAR__',config['singular'].lower()).replace('__GROUP__','AUTOMOTIVE').replace('__OPTIONS__',''.join(f'<option>{s}</option>' for s in statuses)).replace('__CONFIG__',json.dumps(config,ensure_ascii=False))
        (folder/'index.html').write_text(html,encoding='utf-8')
        (folder/'project.json').write_text(json.dumps(config,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
        (folder/'README.md').write_text(f'''# {title}\n\n{desc}\n\nThis is an offline, browser-based working demo. It includes fictional starter records, add/edit/delete, status and text filters, summary cards, and CSV export. Data stays in this browser's local storage. No accounts, cloud sync, external messages, payment processing or third-party connections are configured.\n\n## Run\n\nOpen `index.html` in a recent browser, or serve this folder with `python -m http.server 8000` and open `http://localhost:8000`. No package installation is required.\n\n## Project-specific workflow\n\nRecord **{fields[0]}**, {fields[1].lower()}, and {fields[2].lower()}; update the workflow status and due/activity date; track **{value_label}**; then export the current records as CSV. The sample amounts and records are fictional and intended for demonstration.\n''',encoding='utf-8')
    print(f'Generated {len(PROJECTS)} standalone demo applications.')
if __name__=='__main__': main()
